#ifndef _SYNETINPUT_CONTRACT_H_
#define _SYNETINPUT_CONTRACT_H_

/*
 * Portable GGPO-style input replace contract — SSB64 compatibility shim.
 *
 * The decision core now lives in recomp-net (`recomp_net/input_contract.h`,
 * feat/rollback) as the single shared source. This header only maps BattleShip's
 * existing SYNetInputContract* / syNetInputContract* names onto the RNet* ABI so
 * call sites in port/net/sys/netinput.c stay stable. No SSB64 logic belongs here.
 *
 * Semantics: docs/netplay_input_contract_portable.md + recomp-net docs/rollback.md.
 */

#include <stdint.h>

#include <recomp_net/input_contract.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef RNetInputContractFrame SYNetInputContractFrame;
typedef RNetInputContractParams SYNetInputContractParams;
typedef RNetInputContractHostGates SYNetInputContractHostGates;
typedef RNetInputContractDecision SYNetInputContractDecision;
typedef RNetInputContractCorrectionClass SYNetInputContractCorrectionClass;

#define nSYNetInputContractRewind nRNetInputContractRewind
#define nSYNetInputContractRewindEqualDeferred nRNetInputContractRewindEqualDeferred
#define nSYNetInputContractPromoteEqual nRNetInputContractPromoteEqual
#define nSYNetInputContractPromoteAbsorb nRNetInputContractPromoteAbsorb
#define nSYNetInputContractPromoteProtect nRNetInputContractPromoteProtect
#define nSYNetInputContractPromoteMicro nRNetInputContractPromoteMicro
#define nSYNetInputContractPromoteContinuity nRNetInputContractPromoteContinuity
#define nSYNetInputContractPromoteHashConfirm nRNetInputContractPromoteHashConfirm
#define nSYNetInputContractPromoteDefer nRNetInputContractPromoteDefer
#define nSYNetInputContractPromoteInsignificant nRNetInputContractPromoteInsignificant

#define nSYNetInputContractClassButton nRNetInputContractClassButton
#define nSYNetInputContractClassRelease nRNetInputContractClassRelease
#define nSYNetInputContractClassOnsetFromZero nRNetInputContractClassOnsetFromZero
#define nSYNetInputContractClassMicroStick nRNetInputContractClassMicroStick
#define nSYNetInputContractClassSameIntentContinuity nRNetInputContractClassSameIntentContinuity
#define nSYNetInputContractClassRealStick nRNetInputContractClassRealStick

#define syNetInputContractParamsInitDefaults rnet_input_contract_params_init_defaults
#define syNetInputContractDecisionIsRewind rnet_input_contract_decision_is_rewind
#define syNetInputContractStickLooksAnalog rnet_input_contract_stick_looks_analog
#define syNetInputContractStickSameAnalogIntent rnet_input_contract_stick_same_analog_intent
#define syNetInputContractStickDashGateDisagreeX rnet_input_contract_stick_dash_gate_disagree_x
#define syNetInputContractStickReplaceIsRelease rnet_input_contract_stick_replace_is_release
#define syNetInputContractCorrectionIsSignificant rnet_input_contract_correction_is_significant
#define syNetInputContractClassifyCorrection rnet_input_contract_classify_correction
#define syNetInputContractStickReplaceDecide rnet_input_contract_stick_replace_decide

#ifdef __cplusplus
}
#endif

#endif /* _SYNETINPUT_CONTRACT_H_ */
