#include "port_window_icon.h"

#ifdef __linux__

#include <SDL2/SDL.h>
#include <cstdint>

// stb_image's implementation lives in libultraship's stb_impl.c (see
// HiResPack.cpp). We only need the header.
#include <stb_image.h>

#include "port_icon_data.h"  // generated by tools/embed_icon.py
#include "port_log.h"

namespace ssb64 {

void SetWindowIcon() {
    // SDL_GL_GetCurrentWindow returns the window the active GL context
    // is bound to. On Linux libultraship runs the SDL2 + OpenGL fast3d
    // backend (Metal is macOS-only, DXGI is Windows-only), so by the
    // time this is called — after Ship::Context::InitWindow — the GL
    // context is current on the freshly-created window. On non-GL
    // backends this returns NULL; we treat that as "nothing to do"
    // rather than failing.
    SDL_Window* wnd = SDL_GL_GetCurrentWindow();
    if (!wnd) {
        port_log("SetWindowIcon: SDL_GL_GetCurrentWindow returned NULL — non-GL backend?\n");
        return;
    }

    int w = 0, h = 0, ch = 0;
    std::uint8_t* rgba = stbi_load_from_memory(
        kSSB64IconPng, static_cast<int>(kSSB64IconPng_len), &w, &h, &ch, 4);
    if (!rgba) {
        port_log("SetWindowIcon: stbi_load_from_memory failed (%s)\n",
                 stbi_failure_reason() ? stbi_failure_reason() : "unknown");
        return;
    }

    // SDL byte order for the masks is little-endian-LSB-first; on every
    // platform SDL runs this means R is in the lowest byte of each
    // uint32 pixel laid out as R,G,B,A in memory, which is what
    // stb_image yields.
    SDL_Surface* sfc = SDL_CreateRGBSurfaceFrom(
        rgba, w, h, /*depth=*/32, /*pitch=*/w * 4,
        /*Rmask=*/0x000000FFu,
        /*Gmask=*/0x0000FF00u,
        /*Bmask=*/0x00FF0000u,
        /*Amask=*/0xFF000000u);
    if (!sfc) {
        port_log("SetWindowIcon: SDL_CreateRGBSurfaceFrom failed (%s)\n", SDL_GetError());
        stbi_image_free(rgba);
        return;
    }

    SDL_SetWindowIcon(wnd, sfc);
    SDL_FreeSurface(sfc);   // SDL copies the pixels internally
    stbi_image_free(rgba);
    port_log("SetWindowIcon: applied %dx%d RGBA icon (%zu bytes PNG)\n",
             w, h, kSSB64IconPng_len);
}

}  // namespace ssb64

#else   // !__linux__

namespace ssb64 {
// Windows uses .ico via ssb64.rc, macOS uses .icns in the .app bundle —
// both fire before the app runs, so no SDL-level intervention needed.
void SetWindowIcon() {}
}  // namespace ssb64

#endif  // __linux__
